# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JohnnyG\Documents\CHESS\XRDproject_Python_11June2010Release\dep_prof.ui'
#
# Created: Fri Jun 18 10:17:59 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DepProfDialog(object):
    def setupUi(self, DepProfDialog):
        DepProfDialog.setObjectName("DepProfDialog")
        DepProfDialog.resize(755, 218)
        self.buttonBox = QtGui.QDialogButtonBox(DepProfDialog)
        self.buttonBox.setGeometry(QtCore.QRect(370, 175, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.doubleSpinBoxrate0 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxrate0.setGeometry(QtCore.QRect(120, 35, 91, 25))
        self.doubleSpinBoxrate0.setObjectName("doubleSpinBoxrate0")
        self.lineEditgun0 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditgun0.setGeometry(QtCore.QRect(35, 35, 71, 25))
        self.lineEditgun0.setObjectName("lineEditgun0")
        self.comboBoxdp0 = QtGui.QComboBox(DepProfDialog)
        self.comboBoxdp0.setGeometry(QtCore.QRect(310, 35, 161, 24))
        self.comboBoxdp0.setObjectName("comboBoxdp0")
        self.doubleSpinBoxfrac0 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxfrac0.setGeometry(QtCore.QRect(640, 35, 62, 25))
        self.doubleSpinBoxfrac0.setObjectName("doubleSpinBoxfrac0")
        self.lineEditresp0 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditresp0.setGeometry(QtCore.QRect(525, 35, 113, 25))
        self.lineEditresp0.setObjectName("lineEditresp0")
        self.line = QtGui.QFrame(DepProfDialog)
        self.line.setGeometry(QtCore.QRect(485, 25, 16, 131))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEditresp1 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditresp1.setGeometry(QtCore.QRect(525, 55, 113, 25))
        self.lineEditresp1.setObjectName("lineEditresp1")
        self.doubleSpinBoxfrac1 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxfrac1.setGeometry(QtCore.QRect(640, 55, 62, 25))
        self.doubleSpinBoxfrac1.setObjectName("doubleSpinBoxfrac1")
        self.lineEditresp2 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditresp2.setGeometry(QtCore.QRect(525, 75, 113, 25))
        self.lineEditresp2.setObjectName("lineEditresp2")
        self.doubleSpinBoxfrac3 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxfrac3.setGeometry(QtCore.QRect(640, 95, 62, 25))
        self.doubleSpinBoxfrac3.setObjectName("doubleSpinBoxfrac3")
        self.lineEditresp3 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditresp3.setGeometry(QtCore.QRect(525, 95, 113, 25))
        self.lineEditresp3.setObjectName("lineEditresp3")
        self.doubleSpinBoxfrac2 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxfrac2.setGeometry(QtCore.QRect(640, 75, 62, 25))
        self.doubleSpinBoxfrac2.setObjectName("doubleSpinBoxfrac2")
        self.lineEditresp4 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditresp4.setGeometry(QtCore.QRect(525, 115, 113, 25))
        self.lineEditresp4.setObjectName("lineEditresp4")
        self.doubleSpinBoxfrac5 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxfrac5.setGeometry(QtCore.QRect(640, 135, 62, 25))
        self.doubleSpinBoxfrac5.setObjectName("doubleSpinBoxfrac5")
        self.lineEditresp5 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditresp5.setGeometry(QtCore.QRect(525, 135, 113, 25))
        self.lineEditresp5.setObjectName("lineEditresp5")
        self.doubleSpinBoxfrac4 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxfrac4.setGeometry(QtCore.QRect(640, 115, 62, 25))
        self.doubleSpinBoxfrac4.setObjectName("doubleSpinBoxfrac4")
        self.doubleSpinBoxrate1 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxrate1.setGeometry(QtCore.QRect(120, 65, 91, 25))
        self.doubleSpinBoxrate1.setObjectName("doubleSpinBoxrate1")
        self.lineEditgun1 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditgun1.setGeometry(QtCore.QRect(35, 65, 71, 25))
        self.lineEditgun1.setObjectName("lineEditgun1")
        self.comboBoxdp1 = QtGui.QComboBox(DepProfDialog)
        self.comboBoxdp1.setGeometry(QtCore.QRect(310, 65, 161, 24))
        self.comboBoxdp1.setObjectName("comboBoxdp1")
        self.doubleSpinBoxrate2 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxrate2.setGeometry(QtCore.QRect(120, 95, 91, 25))
        self.doubleSpinBoxrate2.setObjectName("doubleSpinBoxrate2")
        self.lineEditgun2 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditgun2.setGeometry(QtCore.QRect(35, 95, 71, 25))
        self.lineEditgun2.setObjectName("lineEditgun2")
        self.comboBoxdp2 = QtGui.QComboBox(DepProfDialog)
        self.comboBoxdp2.setGeometry(QtCore.QRect(310, 95, 161, 24))
        self.comboBoxdp2.setObjectName("comboBoxdp2")
        self.doubleSpinBoxrate3 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxrate3.setGeometry(QtCore.QRect(120, 125, 91, 25))
        self.doubleSpinBoxrate3.setObjectName("doubleSpinBoxrate3")
        self.lineEditgun3 = QtGui.QLineEdit(DepProfDialog)
        self.lineEditgun3.setGeometry(QtCore.QRect(35, 125, 71, 25))
        self.lineEditgun3.setObjectName("lineEditgun3")
        self.comboBoxdp3 = QtGui.QComboBox(DepProfDialog)
        self.comboBoxdp3.setGeometry(QtCore.QRect(310, 125, 161, 24))
        self.comboBoxdp3.setObjectName("comboBoxdp3")
        self.label = QtGui.QLabel(DepProfDialog)
        self.label.setGeometry(QtCore.QRect(-5, 15, 36, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(DepProfDialog)
        self.label_2.setGeometry(QtCore.QRect(515, 15, 226, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(DepProfDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 35, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(DepProfDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 65, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(DepProfDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 95, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(DepProfDialog)
        self.label_6.setGeometry(QtCore.QRect(10, 125, 16, 16))
        self.label_6.setObjectName("label_6")
        self.doubleSpinBoxvolt0 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxvolt0.setGeometry(QtCore.QRect(220, 35, 91, 25))
        self.doubleSpinBoxvolt0.setMaximum(1000.0)
        self.doubleSpinBoxvolt0.setObjectName("doubleSpinBoxvolt0")
        self.doubleSpinBoxvolt2 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxvolt2.setGeometry(QtCore.QRect(220, 95, 91, 25))
        self.doubleSpinBoxvolt2.setMaximum(1000.0)
        self.doubleSpinBoxvolt2.setObjectName("doubleSpinBoxvolt2")
        self.doubleSpinBoxvolt3 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxvolt3.setGeometry(QtCore.QRect(220, 125, 91, 25))
        self.doubleSpinBoxvolt3.setMaximum(1000.0)
        self.doubleSpinBoxvolt3.setObjectName("doubleSpinBoxvolt3")
        self.doubleSpinBoxvolt1 = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxvolt1.setGeometry(QtCore.QRect(220, 65, 91, 25))
        self.doubleSpinBoxvolt1.setMaximum(1000.0)
        self.doubleSpinBoxvolt1.setObjectName("doubleSpinBoxvolt1")
        self.pushButtonRespCoef = QtGui.QPushButton(DepProfDialog)
        self.pushButtonRespCoef.setGeometry(QtCore.QRect(200, 175, 261, 24))
        self.pushButtonRespCoef.setObjectName("pushButtonRespCoef")
        self.doubleSpinBoxdeptime = QtGui.QDoubleSpinBox(DepProfDialog)
        self.doubleSpinBoxdeptime.setGeometry(QtCore.QRect(80, 170, 91, 25))
        self.doubleSpinBoxdeptime.setMaximum(9999.0)
        self.doubleSpinBoxdeptime.setObjectName("doubleSpinBoxdeptime")
        self.label_7 = QtGui.QLabel(DepProfDialog)
        self.label_7.setGeometry(QtCore.QRect(5, 170, 81, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(DepProfDialog)
        self.label_8.setGeometry(QtCore.QRect(310, 15, 166, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(DepProfDialog)
        self.label_9.setGeometry(QtCore.QRect(215, 15, 91, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(DepProfDialog)
        self.label_10.setGeometry(QtCore.QRect(115, 15, 111, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(DepProfDialog)
        self.label_11.setGeometry(QtCore.QRect(35, 15, 71, 17))
        self.label_11.setObjectName("label_11")

        self.retranslateUi(DepProfDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DepProfDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DepProfDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DepProfDialog)

    def retranslateUi(self, DepProfDialog):
        DepProfDialog.setWindowTitle(QtGui.QApplication.translate("DepProfDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditgun0.setToolTip(QtGui.QApplication.translate("DepProfDialog", "element symbol, case sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxfrac0.setToolTip(QtGui.QApplication.translate("DepProfDialog", "Determines the extent to which the resputter coefficient is used in the composition calculation, i.e. the resputter coefficient used will be coef*frac.", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditresp0.setToolTip(QtGui.QApplication.translate("DepProfDialog", "The element being resputter and the element whose target is reflecting Ar and resputtering the first element.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DepProfDialog", "  gun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DepProfDialog", "resputter coeficient, frac to use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DepProfDialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DepProfDialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DepProfDialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DepProfDialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRespCoef.setText(QtGui.QApplication.translate("DepProfDialog", "Calculate Resputter Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DepProfDialog", "Deposition\n"
"time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DepProfDialog", "Deposition Profile Entry    ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DepProfDialog", " gun voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DepProfDialog", "nmol/s/cm2@ctr  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("DepProfDialog", "element  ", None, QtGui.QApplication.UnicodeUTF8))

