# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JohnnyG\Documents\CHESS\XRDproject_Python\chessrunattr.ui'
#
# Created: Fri Nov 26 23:20:33 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_chessrunattrDialog(object):
    def setupUi(self, chessrunattrDialog):
        chessrunattrDialog.setObjectName("chessrunattrDialog")
        chessrunattrDialog.resize(717, 229)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CUIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        chessrunattrDialog.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(chessrunattrDialog)
        self.buttonBox.setGeometry(QtCore.QRect(520, 195, 160, 26))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_6 = QtGui.QLabel(chessrunattrDialog)
        self.label_6.setGeometry(QtCore.QRect(44, 44, 161, 16))
        self.label_6.setObjectName("label_6")
        self.frame_2 = QtGui.QFrame(chessrunattrDialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 65, 261, 121))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(4, 5, 181, 51))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(4, 80, 256, 16))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(185, 5, 71, 42))
        self.label_8.setObjectName("label_8")
        self.martiltSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.martiltSpinBox.setGeometry(QtCore.QRect(4, 95, 71, 22))
        self.martiltSpinBox.setDecimals(4)
        self.martiltSpinBox.setMaximum(180.0)
        self.martiltSpinBox.setObjectName("martiltSpinBox")
        self.LSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.LSpinBox.setGeometry(QtCore.QRect(180, 50, 71, 22))
        self.LSpinBox.setMaximum(99999.0)
        self.LSpinBox.setObjectName("LSpinBox")
        self.ycenSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.ycenSpinBox.setGeometry(QtCore.QRect(90, 55, 76, 22))
        self.ycenSpinBox.setMaximum(99999.0)
        self.ycenSpinBox.setObjectName("ycenSpinBox")
        self.tiltrotSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.tiltrotSpinBox.setGeometry(QtCore.QRect(100, 95, 62, 22))
        self.tiltrotSpinBox.setMinimum(-360.0)
        self.tiltrotSpinBox.setMaximum(360.0)
        self.tiltrotSpinBox.setObjectName("tiltrotSpinBox")
        self.xcenSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.xcenSpinBox.setGeometry(QtCore.QRect(4, 55, 81, 22))
        self.xcenSpinBox.setMaximum(99999.0)
        self.xcenSpinBox.setObjectName("xcenSpinBox")
        self.frame_3 = QtGui.QFrame(chessrunattrDialog)
        self.frame_3.setGeometry(QtCore.QRect(330, 5, 76, 56))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.alphaSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.alphaSpinBox.setGeometry(QtCore.QRect(0, 30, 65, 22))
        self.alphaSpinBox.setDecimals(2)
        self.alphaSpinBox.setMinimum(-90.0)
        self.alphaSpinBox.setMaximum(90.0)
        self.alphaSpinBox.setObjectName("alphaSpinBox")
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(5, -3, 76, 36))
        self.label_10.setObjectName("label_10")
        self.wavelengthSpinBox = QtGui.QDoubleSpinBox(chessrunattrDialog)
        self.wavelengthSpinBox.setGeometry(QtCore.QRect(550, 151, 77, 21))
        self.wavelengthSpinBox.setDecimals(5)
        self.wavelengthSpinBox.setMaximum(10.0)
        self.wavelengthSpinBox.setSingleStep(0.001)
        self.wavelengthSpinBox.setObjectName("wavelengthSpinBox")
        self.label_12 = QtGui.QLabel(chessrunattrDialog)
        self.label_12.setGeometry(QtCore.QRect(550, 135, 116, 16))
        self.label_12.setObjectName("label_12")
        self.nameLineEdit = QtGui.QLineEdit(chessrunattrDialog)
        self.nameLineEdit.setGeometry(QtCore.QRect(50, 10, 221, 20))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.existingTextBrowser = QtGui.QTextBrowser(chessrunattrDialog)
        self.existingTextBrowser.setGeometry(QtCore.QRect(495, 30, 206, 96))
        self.existingTextBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.existingTextBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.existingTextBrowser.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.existingTextBrowser.setReadOnly(False)
        self.existingTextBrowser.setObjectName("existingTextBrowser")
        self.label = QtGui.QLabel(chessrunattrDialog)
        self.label.setGeometry(QtCore.QRect(5, 15, 46, 14))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(chessrunattrDialog)
        self.label_2.setGeometry(QtCore.QRect(495, 10, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_18 = QtGui.QLabel(chessrunattrDialog)
        self.label_18.setGeometry(QtCore.QRect(275, 65, 176, 61))
        self.label_18.setObjectName("label_18")
        self.tiltdirectionComboBox = QtGui.QComboBox(chessrunattrDialog)
        self.tiltdirectionComboBox.setGeometry(QtCore.QRect(380, 90, 101, 26))
        self.tiltdirectionComboBox.setObjectName("tiltdirectionComboBox")
        self.shape0SpinBox = QtGui.QSpinBox(chessrunattrDialog)
        self.shape0SpinBox.setGeometry(QtCore.QRect(275, 145, 81, 25))
        self.shape0SpinBox.setMinimum(1)
        self.shape0SpinBox.setMaximum(999999)
        self.shape0SpinBox.setProperty("value", QtCore.QVariant(3450))
        self.shape0SpinBox.setObjectName("shape0SpinBox")
        self.shape1SpinBox = QtGui.QSpinBox(chessrunattrDialog)
        self.shape1SpinBox.setGeometry(QtCore.QRect(355, 145, 81, 25))
        self.shape1SpinBox.setMinimum(1)
        self.shape1SpinBox.setMaximum(999999)
        self.shape1SpinBox.setProperty("value", QtCore.QVariant(3450))
        self.shape1SpinBox.setObjectName("shape1SpinBox")
        self.label_3 = QtGui.QLabel(chessrunattrDialog)
        self.label_3.setGeometry(QtCore.QRect(315, 130, 101, 16))
        self.label_3.setObjectName("label_3")
        self.xrdnameLineEdit = QtGui.QLineEdit(chessrunattrDialog)
        self.xrdnameLineEdit.setGeometry(QtCore.QRect(280, 200, 221, 20))
        self.xrdnameLineEdit.setObjectName("xrdnameLineEdit")
        self.label_4 = QtGui.QLabel(chessrunattrDialog)
        self.label_4.setGeometry(QtCore.QRect(285, 185, 291, 16))
        self.label_4.setObjectName("label_4")
        self.label_11 = QtGui.QLabel(chessrunattrDialog)
        self.label_11.setGeometry(QtCore.QRect(445, 120, 71, 42))
        self.label_11.setObjectName("label_11")
        self.psizeSpinBox = QtGui.QDoubleSpinBox(chessrunattrDialog)
        self.psizeSpinBox.setGeometry(QtCore.QRect(440, 160, 71, 22))
        self.psizeSpinBox.setDecimals(3)
        self.psizeSpinBox.setMinimum(-2.0)
        self.psizeSpinBox.setMaximum(99999.0)
        self.psizeSpinBox.setSingleStep(0.1)
        self.psizeSpinBox.setProperty("value", QtCore.QVariant(0.1))
        self.psizeSpinBox.setObjectName("psizeSpinBox")

        self.retranslateUi(chessrunattrDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), chessrunattrDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), chessrunattrDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(chessrunattrDialog)

    def retranslateUi(self, chessrunattrDialog):
        chessrunattrDialog.setWindowTitle(QtGui.QApplication.translate("chessrunattrDialog", "Enter DAQ properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("chessrunattrDialog", "DETECTOR ALIGNMENT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("chessrunattrDialog", "beam center (pixels)\n"
"fit2d,i.e. bottom-left=(1,1)\n"
"horiz (fit2dX) vert(fit2dY)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("chessrunattrDialog", " tilt (deg)      rotation/tilt direction (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("chessrunattrDialog", "detector\n"
"position\n"
"mm", None, QtGui.QApplication.UnicodeUTF8))
        self.martiltSpinBox.setToolTip(QtGui.QApplication.translate("chessrunattrDialog", "As determined from calibrant in Fit2D. The tilt and rotation (rotation is the direction of the tilt) correspond to the non-orthaginality of the detector with respect to the beam. As of July 2010, these fields are never used.", None, QtGui.QApplication.UnicodeUTF8))
        self.LSpinBox.setToolTip(QtGui.QApplication.translate("chessrunattrDialog", "sample to detector distance", None, QtGui.QApplication.UnicodeUTF8))
        self.xcenSpinBox.setToolTip(QtGui.QApplication.translate("chessrunattrDialog", "As determined from calibrant in Fit2D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("chessrunattrDialog", "substrate\n"
"tilt (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("chessrunattrDialog", "wavelength(nm)", None, QtGui.QApplication.UnicodeUTF8))
        self.existingTextBrowser.setToolTip(QtGui.QApplication.translate("chessrunattrDialog", "in the \"name\" field, do not enter a name that already exists", None, QtGui.QApplication.UnicodeUTF8))
        self.existingTextBrowser.setHtml(QtGui.QApplication.translate("chessrunattrDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("chessrunattrDialog", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("chessrunattrDialog", "existing names", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("chessrunattrDialog", "substrate normal is tilted\n"
"towards the\n"
"of the detector", None, QtGui.QApplication.UnicodeUTF8))
        self.tiltdirectionComboBox.setToolTip(QtGui.QApplication.translate("chessrunattrDialog", "Another way to think about this direction - since the substrate is tilted, this is the direction on the detector (looking downstream at the front of the detector) is closest to the substrate.", None, QtGui.QApplication.UnicodeUTF8))
        self.shape0SpinBox.setToolTip(QtGui.QApplication.translate("chessrunattrDialog", "horizontal number of pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.shape1SpinBox.setToolTip(QtGui.QApplication.translate("chessrunattrDialog", "vertical number of pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("chessrunattrDialog", "detector shape", None, QtGui.QApplication.UnicodeUTF8))
        self.xrdnameLineEdit.setText(QtGui.QApplication.translate("chessrunattrDialog", "mar345", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("chessrunattrDialog", "XRD group name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("chessrunattrDialog", "pixel\n"
"size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.psizeSpinBox.setToolTip(QtGui.QApplication.translate("chessrunattrDialog", "sample to detector distance", None, QtGui.QApplication.UnicodeUTF8))

