# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JohnnyG\Documents\CHESS\XRDproject_Python_11June2010Release\import_attr.ui'
#
# Created: Fri Jun 18 10:18:00 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_importattrDialog(object):
    def setupUi(self, importattrDialog):
        importattrDialog.setObjectName("importattrDialog")
        importattrDialog.resize(711, 329)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/backup/CUIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        importattrDialog.setWindowIcon(icon)
        self.cmdLabel = QtGui.QLabel(importattrDialog)
        self.cmdLabel.setGeometry(QtCore.QRect(365, 45, 116, 20))
        self.cmdLabel.setObjectName("cmdLabel")
        self.cmdLineEdit = QtGui.QLineEdit(importattrDialog)
        self.cmdLineEdit.setGeometry(QtCore.QRect(365, 65, 331, 20))
        self.cmdLineEdit.setObjectName("cmdLineEdit")
        self.buttonBox = QtGui.QDialogButtonBox(importattrDialog)
        self.buttonBox.setGeometry(QtCore.QRect(510, 295, 160, 26))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(importattrDialog)
        self.label.setGeometry(QtCore.QRect(538, 183, 61, 29))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(importattrDialog)
        self.label_2.setGeometry(QtCore.QRect(606, 183, 46, 29))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(importattrDialog)
        self.label_3.setGeometry(QtCore.QRect(658, 187, 33, 28))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(importattrDialog)
        self.label_4.setGeometry(QtCore.QRect(470, 219, 57, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(importattrDialog)
        self.label_5.setGeometry(QtCore.QRect(470, 245, 53, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(importattrDialog)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 161, 16))
        self.label_6.setObjectName("label_6")
        self.label_10 = QtGui.QLabel(importattrDialog)
        self.label_10.setGeometry(QtCore.QRect(275, 85, 76, 28))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(importattrDialog)
        self.label_11.setGeometry(QtCore.QRect(325, 190, 151, 28))
        self.label_11.setObjectName("label_11")
        self.calcButton = QtGui.QPushButton(importattrDialog)
        self.calcButton.setGeometry(QtCore.QRect(410, 85, 216, 26))
        self.calcButton.setObjectName("calcButton")
        self.frame_5 = QtGui.QFrame(importattrDialog)
        self.frame_5.setGeometry(QtCore.QRect(510, 120, 151, 41))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.inttimeSpinBox = QtGui.QDoubleSpinBox(self.frame_5)
        self.inttimeSpinBox.setGeometry(QtCore.QRect(80, 10, 61, 22))
        self.inttimeSpinBox.setMinimum(-1e+20)
        self.inttimeSpinBox.setMaximum(1e+20)
        self.inttimeSpinBox.setObjectName("inttimeSpinBox")
        self.integLabel = QtGui.QLabel(self.frame_5)
        self.integLabel.setGeometry(QtCore.QRect(10, 0, 71, 41))
        self.integLabel.setObjectName("integLabel")
        self.label_13 = QtGui.QLabel(importattrDialog)
        self.label_13.setGeometry(QtCore.QRect(40, 35, 71, 16))
        self.label_13.setObjectName("label_13")
        self.el1LineEdit = QtGui.QLineEdit(importattrDialog)
        self.el1LineEdit.setGeometry(QtCore.QRect(0, 50, 41, 20))
        self.el1LineEdit.setObjectName("el1LineEdit")
        self.getchessruninfoButton = QtGui.QPushButton(importattrDialog)
        self.getchessruninfoButton.setGeometry(QtCore.QRect(355, 10, 151, 26))
        self.getchessruninfoButton.setStyleSheet("color:'red'")
        self.getchessruninfoButton.setObjectName("getchessruninfoButton")
        self.frame_2 = QtGui.QFrame(importattrDialog)
        self.frame_2.setGeometry(QtCore.QRect(15, 95, 261, 156))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(4, 5, 186, 46))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(15, 95, 241, 16))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(190, 6, 61, 46))
        self.label_8.setObjectName("label_8")
        self.martiltSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.martiltSpinBox.setGeometry(QtCore.QRect(5, 115, 71, 22))
        self.martiltSpinBox.setReadOnly(True)
        self.martiltSpinBox.setDecimals(4)
        self.martiltSpinBox.setMaximum(180.0)
        self.martiltSpinBox.setObjectName("martiltSpinBox")
        self.LSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.LSpinBox.setGeometry(QtCore.QRect(185, 55, 62, 22))
        self.LSpinBox.setReadOnly(True)
        self.LSpinBox.setMaximum(99999.0)
        self.LSpinBox.setObjectName("LSpinBox")
        self.ycenSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.ycenSpinBox.setGeometry(QtCore.QRect(90, 55, 76, 22))
        self.ycenSpinBox.setReadOnly(True)
        self.ycenSpinBox.setMaximum(99999.0)
        self.ycenSpinBox.setObjectName("ycenSpinBox")
        self.tiltrotSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.tiltrotSpinBox.setGeometry(QtCore.QRect(140, 115, 59, 20))
        self.tiltrotSpinBox.setReadOnly(True)
        self.tiltrotSpinBox.setMinimum(-360.0)
        self.tiltrotSpinBox.setMaximum(360.0)
        self.tiltrotSpinBox.setObjectName("tiltrotSpinBox")
        self.xcenSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.xcenSpinBox.setGeometry(QtCore.QRect(4, 55, 81, 22))
        self.xcenSpinBox.setReadOnly(True)
        self.xcenSpinBox.setMaximum(99999.0)
        self.xcenSpinBox.setObjectName("xcenSpinBox")
        self.xstartSpinBox = QtGui.QDoubleSpinBox(importattrDialog)
        self.xstartSpinBox.setGeometry(QtCore.QRect(530, 215, 61, 22))
        self.xstartSpinBox.setMinimum(-99999.0)
        self.xstartSpinBox.setMaximum(99999.0)
        self.xstartSpinBox.setObjectName("xstartSpinBox")
        self.zstartSpinBox = QtGui.QDoubleSpinBox(importattrDialog)
        self.zstartSpinBox.setGeometry(QtCore.QRect(530, 239, 61, 22))
        self.zstartSpinBox.setMinimum(-99999.0)
        self.zstartSpinBox.setMaximum(99999.0)
        self.zstartSpinBox.setObjectName("zstartSpinBox")
        self.zintSpinBox = QtGui.QDoubleSpinBox(importattrDialog)
        self.zintSpinBox.setGeometry(QtCore.QRect(590, 239, 61, 22))
        self.zintSpinBox.setMinimum(-9999.0)
        self.zintSpinBox.setMaximum(99999.0)
        self.zintSpinBox.setObjectName("zintSpinBox")
        self.xptsSpinBox = QtGui.QSpinBox(importattrDialog)
        self.xptsSpinBox.setGeometry(QtCore.QRect(654, 215, 46, 22))
        self.xptsSpinBox.setMaximum(99999)
        self.xptsSpinBox.setObjectName("xptsSpinBox")
        self.zptsSpinBox = QtGui.QSpinBox(importattrDialog)
        self.zptsSpinBox.setGeometry(QtCore.QRect(654, 239, 46, 22))
        self.zptsSpinBox.setMaximum(99999)
        self.zptsSpinBox.setObjectName("zptsSpinBox")
        self.xintSpinBox = QtGui.QDoubleSpinBox(importattrDialog)
        self.xintSpinBox.setGeometry(QtCore.QRect(590, 215, 61, 22))
        self.xintSpinBox.setMinimum(-99999.0)
        self.xintSpinBox.setMaximum(99999.0)
        self.xintSpinBox.setObjectName("xintSpinBox")
        self.bckndComboBox = QtGui.QComboBox(importattrDialog)
        self.bckndComboBox.setGeometry(QtCore.QRect(325, 210, 131, 22))
        self.bckndComboBox.setObjectName("bckndComboBox")
        self.bckndComboBox.addItem(QtCore.QString())
        self.bckndComboBox.addItem(QtCore.QString())
        self.bckndComboBox.addItem(QtCore.QString())
        self.wavelengthSpinBox = QtGui.QDoubleSpinBox(importattrDialog)
        self.wavelengthSpinBox.setGeometry(QtCore.QRect(190, 55, 91, 21))
        self.wavelengthSpinBox.setReadOnly(True)
        self.wavelengthSpinBox.setDecimals(5)
        self.wavelengthSpinBox.setMaximum(10.0)
        self.wavelengthSpinBox.setSingleStep(0.001)
        self.wavelengthSpinBox.setObjectName("wavelengthSpinBox")
        self.label_12 = QtGui.QLabel(importattrDialog)
        self.label_12.setGeometry(QtCore.QRect(190, 40, 121, 16))
        self.label_12.setObjectName("label_12")
        self.alphaSpinBox = QtGui.QDoubleSpinBox(importattrDialog)
        self.alphaSpinBox.setGeometry(QtCore.QRect(270, 115, 65, 22))
        self.alphaSpinBox.setReadOnly(True)
        self.alphaSpinBox.setDecimals(2)
        self.alphaSpinBox.setMinimum(-90.0)
        self.alphaSpinBox.setMaximum(90.0)
        self.alphaSpinBox.setObjectName("alphaSpinBox")
        self.chessruncomboBox = QtGui.QComboBox(importattrDialog)
        self.chessruncomboBox.setGeometry(QtCore.QRect(100, 10, 251, 22))
        self.chessruncomboBox.setObjectName("chessruncomboBox")
        self.label_14 = QtGui.QLabel(importattrDialog)
        self.label_14.setGeometry(QtCore.QRect(35, 10, 76, 20))
        self.label_14.setObjectName("label_14")
        self.imapcomboBox = QtGui.QComboBox(importattrDialog)
        self.imapcomboBox.setGeometry(QtCore.QRect(60, 260, 311, 22))
        self.imapcomboBox.setObjectName("imapcomboBox")
        self.label_15 = QtGui.QLabel(importattrDialog)
        self.label_15.setGeometry(QtCore.QRect(20, 260, 51, 20))
        self.label_15.setObjectName("label_15")
        self.chimapcomboBox = QtGui.QComboBox(importattrDialog)
        self.chimapcomboBox.setGeometry(QtCore.QRect(60, 280, 311, 22))
        self.chimapcomboBox.setObjectName("chimapcomboBox")
        self.label_16 = QtGui.QLabel(importattrDialog)
        self.label_16.setGeometry(QtCore.QRect(5, 280, 56, 20))
        self.label_16.setObjectName("label_16")
        self.killmapcomboBox = QtGui.QComboBox(importattrDialog)
        self.killmapcomboBox.setGeometry(QtCore.QRect(60, 300, 311, 22))
        self.killmapcomboBox.setObjectName("killmapcomboBox")
        self.label_17 = QtGui.QLabel(importattrDialog)
        self.label_17.setGeometry(QtCore.QRect(5, 300, 56, 20))
        self.label_17.setObjectName("label_17")
        self.usespecCheckBox = QtGui.QCheckBox(importattrDialog)
        self.usespecCheckBox.setGeometry(QtCore.QRect(350, 125, 146, 31))
        self.usespecCheckBox.setChecked(True)
        self.usespecCheckBox.setObjectName("usespecCheckBox")
        self.el2LineEdit = QtGui.QLineEdit(importattrDialog)
        self.el2LineEdit.setGeometry(QtCore.QRect(40, 50, 41, 20))
        self.el2LineEdit.setObjectName("el2LineEdit")
        self.el3LineEdit = QtGui.QLineEdit(importattrDialog)
        self.el3LineEdit.setGeometry(QtCore.QRect(80, 50, 41, 20))
        self.el3LineEdit.setObjectName("el3LineEdit")
        self.el4LineEdit = QtGui.QLineEdit(importattrDialog)
        self.el4LineEdit.setGeometry(QtCore.QRect(120, 50, 41, 20))
        self.el4LineEdit.setObjectName("el4LineEdit")

        self.retranslateUi(importattrDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), importattrDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), importattrDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(importattrDialog)
        importattrDialog.setTabOrder(self.el1LineEdit, self.el2LineEdit)
        importattrDialog.setTabOrder(self.el2LineEdit, self.el3LineEdit)
        importattrDialog.setTabOrder(self.el3LineEdit, self.el4LineEdit)
        importattrDialog.setTabOrder(self.el4LineEdit, self.killmapcomboBox)
        importattrDialog.setTabOrder(self.killmapcomboBox, self.buttonBox)
        importattrDialog.setTabOrder(self.buttonBox, self.chessruncomboBox)
        importattrDialog.setTabOrder(self.chessruncomboBox, self.getchessruninfoButton)
        importattrDialog.setTabOrder(self.getchessruninfoButton, self.wavelengthSpinBox)
        importattrDialog.setTabOrder(self.wavelengthSpinBox, self.cmdLineEdit)
        importattrDialog.setTabOrder(self.cmdLineEdit, self.calcButton)
        importattrDialog.setTabOrder(self.calcButton, self.alphaSpinBox)
        importattrDialog.setTabOrder(self.alphaSpinBox, self.xcenSpinBox)
        importattrDialog.setTabOrder(self.xcenSpinBox, self.ycenSpinBox)
        importattrDialog.setTabOrder(self.ycenSpinBox, self.LSpinBox)
        importattrDialog.setTabOrder(self.LSpinBox, self.martiltSpinBox)
        importattrDialog.setTabOrder(self.martiltSpinBox, self.tiltrotSpinBox)
        importattrDialog.setTabOrder(self.tiltrotSpinBox, self.bckndComboBox)
        importattrDialog.setTabOrder(self.bckndComboBox, self.xptsSpinBox)
        importattrDialog.setTabOrder(self.xptsSpinBox, self.imapcomboBox)
        importattrDialog.setTabOrder(self.imapcomboBox, self.zptsSpinBox)
        importattrDialog.setTabOrder(self.zptsSpinBox, self.inttimeSpinBox)
        importattrDialog.setTabOrder(self.inttimeSpinBox, self.xstartSpinBox)
        importattrDialog.setTabOrder(self.xstartSpinBox, self.xintSpinBox)
        importattrDialog.setTabOrder(self.xintSpinBox, self.usespecCheckBox)
        importattrDialog.setTabOrder(self.usespecCheckBox, self.chimapcomboBox)
        importattrDialog.setTabOrder(self.chimapcomboBox, self.zstartSpinBox)
        importattrDialog.setTabOrder(self.zstartSpinBox, self.zintSpinBox)

    def retranslateUi(self, importattrDialog):
        importattrDialog.setWindowTitle(QtGui.QApplication.translate("importattrDialog", "Enter DAQ properties", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdLabel.setText(QtGui.QApplication.translate("importattrDialog", "spec command", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdLineEdit.setText(QtGui.QApplication.translate("importattrDialog", "mesh samx -36 36 13 samz -36 36 13 45", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("importattrDialog", "start value\n"
"(mm) <low>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("importattrDialog", "interval\n"
"(mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("importattrDialog", "# of\n"
"points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("importattrDialog", "x-horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("importattrDialog", "z-vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("importattrDialog", "DETECTOR ALIGNMENT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("importattrDialog", "substrate\n"
"tilt (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("importattrDialog", "background algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.calcButton.setText(QtGui.QApplication.translate("importattrDialog", "^ calculate grid parameters ->", None, QtGui.QApplication.UnicodeUTF8))
        self.integLabel.setText(QtGui.QApplication.translate("importattrDialog", "integration\n"
"time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("importattrDialog", "Elements:", None, QtGui.QApplication.UnicodeUTF8))
        self.el1LineEdit.setToolTip(QtGui.QApplication.translate("importattrDialog", "The elements in the film should be entered with 1 element symbol per box. The order only matters for deposition profile calculations.", None, QtGui.QApplication.UnicodeUTF8))
        self.getchessruninfoButton.setText(QtGui.QApplication.translate("importattrDialog", "get chessrun info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("importattrDialog", "beam center (pixels)\n"
"fit2d,i.e. bottom-left=(1,1)\n"
"horiz (fit2dX) vert(fit2dY)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("importattrDialog", " tilt (deg)  rotation/tilt direction (deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("importattrDialog", "detector\n"
"position\n"
"mm", None, QtGui.QApplication.UnicodeUTF8))
        self.martiltSpinBox.setToolTip(QtGui.QApplication.translate("importattrDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">As determined from calibrant in Fit2D. The tilt and rotation (rotation is the direction of the tilt) correspond to the non-orthaginality of the detector with respect to the beam. As of July 2010, these fields are never used.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LSpinBox.setToolTip(QtGui.QApplication.translate("importattrDialog", "sample to detector distance", None, QtGui.QApplication.UnicodeUTF8))
        self.xcenSpinBox.setToolTip(QtGui.QApplication.translate("importattrDialog", "As determined from calibrant in Fit2D", None, QtGui.QApplication.UnicodeUTF8))
        self.bckndComboBox.setItemText(0, QtGui.QApplication.translate("importattrDialog", "minanom", None, QtGui.QApplication.UnicodeUTF8))
        self.bckndComboBox.setItemText(1, QtGui.QApplication.translate("importattrDialog", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.bckndComboBox.setItemText(2, QtGui.QApplication.translate("importattrDialog", "ave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("importattrDialog", "wavelength(nm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("importattrDialog", "chessrun:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("importattrDialog", "imap:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("importattrDialog", "chimap:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("importattrDialog", "killmap:", None, QtGui.QApplication.UnicodeUTF8))
        self.usespecCheckBox.setToolTip(QtGui.QApplication.translate("importattrDialog", "Unless you need to make a manual adjustment and you know what you are doing, leave this checked and ignore everything to the right of this box, i.e. \"spec command\" through \"# of points\"", None, QtGui.QApplication.UnicodeUTF8))
        self.usespecCheckBox.setText(QtGui.QApplication.translate("importattrDialog", "Use existing spec\n"
"acquisition info", None, QtGui.QApplication.UnicodeUTF8))

