# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JohnnyG\Documents\CHESS\XRDproject_Python_11June2010Release\waveset1d_params.ui'
#
# Created: Fri Jun 18 10:18:02 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_waveset1d_params_Dialog(object):
    def setupUi(self, waveset1d_params_Dialog):
        waveset1d_params_Dialog.setObjectName("waveset1d_params_Dialog")
        waveset1d_params_Dialog.resize(413, 237)
        self.qpminSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qpminSpinBox.setGeometry(QtCore.QRect(120, 95, 71, 20))
        self.qpminSpinBox.setMaximum(99999.0)
        self.qpminSpinBox.setProperty("value", QtCore.QVariant(20.0))
        self.qpminSpinBox.setObjectName("qpminSpinBox")
        self.qpmaxSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qpmaxSpinBox.setGeometry(QtCore.QRect(190, 95, 71, 20))
        self.qpmaxSpinBox.setMaximum(99999.0)
        self.qpmaxSpinBox.setProperty("value", QtCore.QVariant(95.0))
        self.qpmaxSpinBox.setObjectName("qpmaxSpinBox")
        self.qpintSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qpintSpinBox.setGeometry(QtCore.QRect(260, 95, 71, 20))
        self.qpintSpinBox.setMaximum(99999.0)
        self.qpintSpinBox.setProperty("value", QtCore.QVariant(0.1))
        self.qpintSpinBox.setObjectName("qpintSpinBox")
        self.qminSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qminSpinBox.setGeometry(QtCore.QRect(120, 115, 71, 20))
        self.qminSpinBox.setMaximum(99999.0)
        self.qminSpinBox.setObjectName("qminSpinBox")
        self.qmaxSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qmaxSpinBox.setGeometry(QtCore.QRect(190, 115, 71, 20))
        self.qmaxSpinBox.setMaximum(99999.0)
        self.qmaxSpinBox.setObjectName("qmaxSpinBox")
        self.qintSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qintSpinBox.setGeometry(QtCore.QRect(260, 115, 71, 20))
        self.qintSpinBox.setMaximum(99999.0)
        self.qintSpinBox.setObjectName("qintSpinBox")
        self.label_5 = QtGui.QLabel(waveset1d_params_Dialog)
        self.label_5.setGeometry(QtCore.QRect(5, 75, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(waveset1d_params_Dialog)
        self.label_6.setGeometry(QtCore.QRect(5, 95, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(waveset1d_params_Dialog)
        self.label_7.setGeometry(QtCore.QRect(15, 115, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(waveset1d_params_Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 145, 291, 46))
        self.label_8.setObjectName("label_8")
        self.fixenSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.fixenSpinBox.setGeometry(QtCore.QRect(285, 160, 71, 20))
        self.fixenSpinBox.setMaximum(1.0)
        self.fixenSpinBox.setProperty("value", QtCore.QVariant(0.12))
        self.fixenSpinBox.setObjectName("fixenSpinBox")
        self.label_2 = QtGui.QLabel(waveset1d_params_Dialog)
        self.label_2.setGeometry(QtCore.QRect(210, 55, 31, 17))
        self.label_2.setObjectName("label_2")
        self.buttonBox = QtGui.QDialogButtonBox(waveset1d_params_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 200, 225, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.qsmaxSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qsmaxSpinBox.setGeometry(QtCore.QRect(190, 75, 71, 20))
        self.qsmaxSpinBox.setMaximum(99999.0)
        self.qsmaxSpinBox.setProperty("value", QtCore.QVariant(3.82))
        self.qsmaxSpinBox.setObjectName("qsmaxSpinBox")
        self.label = QtGui.QLabel(waveset1d_params_Dialog)
        self.label.setGeometry(QtCore.QRect(143, 56, 21, 17))
        self.label.setObjectName("label")
        self.label_4 = QtGui.QLabel(waveset1d_params_Dialog)
        self.label_4.setGeometry(QtCore.QRect(140, 5, 201, 51))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtGui.QLabel(waveset1d_params_Dialog)
        self.label_3.setGeometry(QtCore.QRect(270, 55, 66, 17))
        self.label_3.setObjectName("label_3")
        self.qsintSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qsintSpinBox.setGeometry(QtCore.QRect(260, 75, 71, 20))
        self.qsintSpinBox.setMaximum(99999.0)
        self.qsintSpinBox.setProperty("value", QtCore.QVariant(1.18))
        self.qsintSpinBox.setObjectName("qsintSpinBox")
        self.qsminSpinBox = QtGui.QDoubleSpinBox(waveset1d_params_Dialog)
        self.qsminSpinBox.setGeometry(QtCore.QRect(120, 75, 71, 20))
        self.qsminSpinBox.setMaximum(99999.0)
        self.qsminSpinBox.setProperty("value", QtCore.QVariant(0.1))
        self.qsminSpinBox.setObjectName("qsminSpinBox")

        self.retranslateUi(waveset1d_params_Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), waveset1d_params_Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), waveset1d_params_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(waveset1d_params_Dialog)

    def retranslateUi(self, waveset1d_params_Dialog):
        waveset1d_params_Dialog.setWindowTitle(QtGui.QApplication.translate("waveset1d_params_Dialog", "Enter integration map parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.qpminSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "This must be larger than the min of \"values of data\"", None, QtGui.QApplication.UnicodeUTF8))
        self.qpmaxSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "This must be smaller than the max of \"values of data\"", None, QtGui.QApplication.UnicodeUTF8))
        self.qpintSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "This must an integer multiple of the interval of \"values of data\"", None, QtGui.QApplication.UnicodeUTF8))
        self.qminSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "The \"values of data\" entires were filled in according to your .h5, spec group, and \"type of data\" selection.", None, QtGui.QApplication.UnicodeUTF8))
        self.qmaxSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "The \"values of data\" entires were filled in according to your .h5, spec group, and \"type of data\" selection.", None, QtGui.QApplication.UnicodeUTF8))
        self.qintSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "The \"values of data\" entires were filled in according to your .h5, spec group, and \"type of data\" selection. ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("waveset1d_params_Dialog", "scale of wavelet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("waveset1d_params_Dialog", "posn of wavelet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("waveset1d_params_Dialog", "values of data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("waveset1d_params_Dialog", "max fractional deviation from continuous\n"
"energy for wavelet to be corrected\n"
"and included in wavelet set", None, QtGui.QApplication.UnicodeUTF8))
        self.fixenSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "For wavelets that go off the edge of the dataset or are at a fine scale with respect to the interval, the wavelet may be \"corrected\" to restored the null zeroth and first moments. This determined the amount of \"correction\" that is allowed - wavelets that are too far off from their continuous counterparts are not used in the wavelet transform.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("waveset1d_params_Dialog", "max", None, QtGui.QApplication.UnicodeUTF8))
        self.qsmaxSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "This should be ~3* the largest peak width you anticipate.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("waveset1d_params_Dialog", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("waveset1d_params_Dialog", "ENTER ALL VALUES IN 2pi/nm\n"
"(except scale interval,\n"
"which is the log interval)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("waveset1d_params_Dialog", " interval", None, QtGui.QApplication.UnicodeUTF8))
        self.qsintSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "The wavelet scales will be spaced in powers of this interval. 1.18 should always be a resonable value", None, QtGui.QApplication.UnicodeUTF8))
        self.qsminSpinBox.setToolTip(QtGui.QApplication.translate("waveset1d_params_Dialog", "This is the \"half-width\" of the LoG wavelet and should be >4* the interval of \"values of data\"", None, QtGui.QApplication.UnicodeUTF8))

