# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JohnnyG\Documents\CHESS\XRDproject_Python_11June2010Release\xrf_analysis.ui'
#
# Created: Fri Jun 18 10:18:02 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_XRFAnalysisDialog(object):
    def setupUi(self, XRFAnalysisDialog):
        XRFAnalysisDialog.setObjectName("XRFAnalysisDialog")
        XRFAnalysisDialog.resize(755, 631)
        self.buttonBox = QtGui.QDialogButtonBox(XRFAnalysisDialog)
        self.buttonBox.setGeometry(QtCore.QRect(525, 595, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.FluxIndComboBox = QtGui.QComboBox(XRFAnalysisDialog)
        self.FluxIndComboBox.setGeometry(QtCore.QRect(570, 70, 81, 24))
        self.FluxIndComboBox.setObjectName("FluxIndComboBox")
        self.FluxSpinBox = QtGui.QDoubleSpinBox(XRFAnalysisDialog)
        self.FluxSpinBox.setGeometry(QtCore.QRect(570, 50, 81, 25))
        self.FluxSpinBox.setDecimals(0)
        self.FluxSpinBox.setMaximum(999999999.0)
        self.FluxSpinBox.setObjectName("FluxSpinBox")
        self.label_2 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_2.setGeometry(QtCore.QRect(430, 10, 191, 21))
        self.label_2.setObjectName("label_2")
        self.DepProfEstCheckBox = QtGui.QCheckBox(XRFAnalysisDialog)
        self.DepProfEstCheckBox.setGeometry(QtCore.QRect(100, 50, 181, 23))
        self.DepProfEstCheckBox.setObjectName("DepProfEstCheckBox")
        self.ElLineEdit0 = QtGui.QLineEdit(XRFAnalysisDialog)
        self.ElLineEdit0.setGeometry(QtCore.QRect(10, 20, 71, 25))
        self.ElLineEdit0.setObjectName("ElLineEdit0")
        self.ElLineEdit1 = QtGui.QLineEdit(XRFAnalysisDialog)
        self.ElLineEdit1.setGeometry(QtCore.QRect(80, 20, 71, 25))
        self.ElLineEdit1.setObjectName("ElLineEdit1")
        self.ElLineEdit2 = QtGui.QLineEdit(XRFAnalysisDialog)
        self.ElLineEdit2.setGeometry(QtCore.QRect(150, 20, 71, 25))
        self.ElLineEdit2.setObjectName("ElLineEdit2")
        self.ElLineEdit3 = QtGui.QLineEdit(XRFAnalysisDialog)
        self.ElLineEdit3.setGeometry(QtCore.QRect(220, 20, 71, 25))
        self.ElLineEdit3.setObjectName("ElLineEdit3")
        self.label = QtGui.QLabel(XRFAnalysisDialog)
        self.label.setGeometry(QtCore.QRect(140, 5, 101, 16))
        self.label.setObjectName("label")
        self.UnderLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.UnderLineEdit.setGeometry(QtCore.QRect(130, 140, 71, 25))
        self.UnderLineEdit.setObjectName("UnderLineEdit")
        self.UnderSpinBox = QtGui.QDoubleSpinBox(XRFAnalysisDialog)
        self.UnderSpinBox.setGeometry(QtCore.QRect(220, 140, 62, 25))
        self.UnderSpinBox.setDecimals(0)
        self.UnderSpinBox.setMaximum(9999.0)
        self.UnderSpinBox.setObjectName("UnderSpinBox")
        self.SicmSpinBox = QtGui.QDoubleSpinBox(XRFAnalysisDialog)
        self.SicmSpinBox.setGeometry(QtCore.QRect(10, 140, 81, 25))
        self.SicmSpinBox.setDecimals(4)
        self.SicmSpinBox.setSingleStep(0.01)
        self.SicmSpinBox.setObjectName("SicmSpinBox")
        self.label_3 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_4.setGeometry(QtCore.QRect(140, 100, 186, 51))
        self.label_4.setObjectName("label_4")
        self.radioButtonDef = QtGui.QRadioButton(XRFAnalysisDialog)
        self.radioButtonDef.setGeometry(QtCore.QRect(420, 30, 121, 21))
        self.radioButtonDef.setChecked(True)
        self.radioButtonDef.setObjectName("radioButtonDef")
        self.radioButtonEnt = QtGui.QRadioButton(XRFAnalysisDialog)
        self.radioButtonEnt.setGeometry(QtCore.QRect(420, 50, 111, 21))
        self.radioButtonEnt.setObjectName("radioButtonEnt")
        self.radioButtonInd = QtGui.QRadioButton(XRFAnalysisDialog)
        self.radioButtonInd.setGeometry(QtCore.QRect(420, 70, 171, 21))
        self.radioButtonInd.setObjectName("radioButtonInd")
        self.cfgComboBox = QtGui.QComboBox(XRFAnalysisDialog)
        self.cfgComboBox.setGeometry(QtCore.QRect(460, 140, 201, 24))
        self.cfgComboBox.setObjectName("cfgComboBox")
        self.label_5 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_5.setGeometry(QtCore.QRect(320, 140, 136, 21))
        self.label_5.setObjectName("label_5")
        self.chessrunComboBox = QtGui.QComboBox(XRFAnalysisDialog)
        self.chessrunComboBox.setGeometry(QtCore.QRect(150, 80, 161, 24))
        self.chessrunComboBox.setObjectName("chessrunComboBox")
        self.label_6 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 121, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_7.setGeometry(QtCore.QRect(25, 250, 276, 16))
        self.label_7.setObjectName("label_7")
        self.alreadyinlistLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.alreadyinlistLineEdit.setGeometry(QtCore.QRect(305, 250, 361, 25))
        self.alreadyinlistLineEdit.setObjectName("alreadyinlistLineEdit")
        self.label_8 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_8.setGeometry(QtCore.QRect(155, 280, 141, 16))
        self.label_8.setObjectName("label_8")
        self.fitLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.fitLineEdit.setGeometry(QtCore.QRect(305, 280, 361, 25))
        self.fitLineEdit.setObjectName("fitLineEdit")
        self.label_9 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_9.setGeometry(QtCore.QRect(120, 310, 186, 16))
        self.label_9.setObjectName("label_9")
        self.quantLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.quantLineEdit.setGeometry(QtCore.QRect(305, 310, 361, 25))
        self.quantLineEdit.setObjectName("quantLineEdit")
        self.label_10 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_10.setGeometry(QtCore.QRect(35, 340, 266, 16))
        self.label_10.setObjectName("label_10")
        self.bckndLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.bckndLineEdit.setGeometry(QtCore.QRect(305, 340, 361, 25))
        self.bckndLineEdit.setObjectName("bckndLineEdit")
        self.enminSpinBox = QtGui.QDoubleSpinBox(XRFAnalysisDialog)
        self.enminSpinBox.setGeometry(QtCore.QRect(80, 210, 81, 25))
        self.enminSpinBox.setObjectName("enminSpinBox")
        self.enmaxSpinBox = QtGui.QDoubleSpinBox(XRFAnalysisDialog)
        self.enmaxSpinBox.setGeometry(QtCore.QRect(160, 210, 91, 25))
        self.enmaxSpinBox.setObjectName("enmaxSpinBox")
        self.label_11 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_11.setGeometry(QtCore.QRect(65, 180, 231, 31))
        self.label_11.setObjectName("label_11")
        self.transitionsPushButton = QtGui.QPushButton(XRFAnalysisDialog)
        self.transitionsPushButton.setGeometry(QtCore.QRect(335, 200, 236, 31))
        self.transitionsPushButton.setObjectName("transitionsPushButton")
        self.label_12 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_12.setGeometry(QtCore.QRect(120, 370, 186, 16))
        self.label_12.setObjectName("label_12")
        self.densityLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.densityLineEdit.setGeometry(QtCore.QRect(305, 370, 361, 25))
        self.densityLineEdit.setObjectName("densityLineEdit")
        self.label_13 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_13.setGeometry(QtCore.QRect(130, 400, 176, 16))
        self.label_13.setObjectName("label_13")
        self.massLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.massLineEdit.setGeometry(QtCore.QRect(305, 400, 361, 25))
        self.massLineEdit.setObjectName("massLineEdit")
        self.label_14 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_14.setGeometry(QtCore.QRect(35, 430, 266, 16))
        self.label_14.setObjectName("label_14")
        self.compLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.compLineEdit.setGeometry(QtCore.QRect(305, 430, 361, 25))
        self.compLineEdit.setObjectName("compLineEdit")
        self.timeLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.timeLineEdit.setGeometry(QtCore.QRect(585, 105, 71, 25))
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.label_15 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_15.setGeometry(QtCore.QRect(360, 110, 226, 16))
        self.label_15.setObjectName("label_15")
        self.ElLineEdit4 = QtGui.QLineEdit(XRFAnalysisDialog)
        self.ElLineEdit4.setGeometry(QtCore.QRect(290, 20, 71, 25))
        self.ElLineEdit4.setObjectName("ElLineEdit4")
        self.repenLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.repenLineEdit.setGeometry(QtCore.QRect(305, 460, 361, 25))
        self.repenLineEdit.setObjectName("repenLineEdit")
        self.label_16 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_16.setGeometry(QtCore.QRect(50, 460, 251, 16))
        self.label_16.setObjectName("label_16")
        self.mflambdaLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.mflambdaLineEdit.setGeometry(QtCore.QRect(40, 555, 691, 25))
        self.mflambdaLineEdit.setObjectName("mflambdaLineEdit")
        self.dlambdaLineEdit = QtGui.QLineEdit(XRFAnalysisDialog)
        self.dlambdaLineEdit.setGeometry(QtCore.QRect(40, 510, 691, 25))
        self.dlambdaLineEdit.setObjectName("dlambdaLineEdit")
        self.label_20 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_20.setGeometry(QtCore.QRect(50, 540, 611, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(XRFAnalysisDialog)
        self.label_21.setGeometry(QtCore.QRect(50, 495, 231, 16))
        self.label_21.setObjectName("label_21")

        self.retranslateUi(XRFAnalysisDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), XRFAnalysisDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), XRFAnalysisDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(XRFAnalysisDialog)
        XRFAnalysisDialog.setTabOrder(self.ElLineEdit0, self.ElLineEdit1)
        XRFAnalysisDialog.setTabOrder(self.ElLineEdit1, self.ElLineEdit2)
        XRFAnalysisDialog.setTabOrder(self.ElLineEdit2, self.ElLineEdit3)
        XRFAnalysisDialog.setTabOrder(self.ElLineEdit3, self.ElLineEdit4)
        XRFAnalysisDialog.setTabOrder(self.ElLineEdit4, self.chessrunComboBox)
        XRFAnalysisDialog.setTabOrder(self.chessrunComboBox, self.SicmSpinBox)
        XRFAnalysisDialog.setTabOrder(self.SicmSpinBox, self.UnderLineEdit)
        XRFAnalysisDialog.setTabOrder(self.UnderLineEdit, self.UnderSpinBox)
        XRFAnalysisDialog.setTabOrder(self.UnderSpinBox, self.transitionsPushButton)
        XRFAnalysisDialog.setTabOrder(self.transitionsPushButton, self.alreadyinlistLineEdit)
        XRFAnalysisDialog.setTabOrder(self.alreadyinlistLineEdit, self.fitLineEdit)
        XRFAnalysisDialog.setTabOrder(self.fitLineEdit, self.quantLineEdit)
        XRFAnalysisDialog.setTabOrder(self.quantLineEdit, self.bckndLineEdit)
        XRFAnalysisDialog.setTabOrder(self.bckndLineEdit, self.densityLineEdit)
        XRFAnalysisDialog.setTabOrder(self.densityLineEdit, self.massLineEdit)
        XRFAnalysisDialog.setTabOrder(self.massLineEdit, self.compLineEdit)
        XRFAnalysisDialog.setTabOrder(self.compLineEdit, self.enminSpinBox)
        XRFAnalysisDialog.setTabOrder(self.enminSpinBox, self.enmaxSpinBox)
        XRFAnalysisDialog.setTabOrder(self.enmaxSpinBox, self.radioButtonInd)
        XRFAnalysisDialog.setTabOrder(self.radioButtonInd, self.radioButtonDef)
        XRFAnalysisDialog.setTabOrder(self.radioButtonDef, self.radioButtonEnt)
        XRFAnalysisDialog.setTabOrder(self.radioButtonEnt, self.DepProfEstCheckBox)
        XRFAnalysisDialog.setTabOrder(self.DepProfEstCheckBox, self.cfgComboBox)
        XRFAnalysisDialog.setTabOrder(self.cfgComboBox, self.FluxIndComboBox)
        XRFAnalysisDialog.setTabOrder(self.FluxIndComboBox, self.FluxSpinBox)
        XRFAnalysisDialog.setTabOrder(self.FluxSpinBox, self.timeLineEdit)
        XRFAnalysisDialog.setTabOrder(self.timeLineEdit, self.buttonBox)

    def retranslateUi(self, XRFAnalysisDialog):
        XRFAnalysisDialog.setWindowTitle(QtGui.QApplication.translate("XRFAnalysisDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "flux determination method", None, QtGui.QApplication.UnicodeUTF8))
        self.DepProfEstCheckBox.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Use Dep. Profile Estimates", None, QtGui.QApplication.UnicodeUTF8))
        self.ElLineEdit0.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "These are element symbols. Below, the transtitions for these elements will be added to the fit and quant lists.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Film elements ", None, QtGui.QApplication.UnicodeUTF8))
        self.UnderSpinBox.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "If there is no underlayer, m ake the thickness 0.", None, QtGui.QApplication.UnicodeUTF8))
        self.SicmSpinBox.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "This menu assumes a geometry of, from upstream to downstream, Si substrate/underlayer thin film/composition spread thin film.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Si thickness (cm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "        Underlayer\n"
"Element   | Thickness (nm)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonDef.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Use Default", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonEnt.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Enter value", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonInd.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Calibrate to index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "base pymca.cfg file:", None, QtGui.QApplication.UnicodeUTF8))
        self.chessrunComboBox.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "If you click on one of these menu items, the defaults indiicated in the .txt library will be loaded into the surrounding fields.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "defaults to load:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Quant transitions already in defaultfit list:", None, QtGui.QApplication.UnicodeUTF8))
        self.alreadyinlistLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "In the .cfg file, there may be \"background\" elements that are detected even when the element is not present in the thin film. If these elements are additionally being included in the thin film model, the transitions will be listed here.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Xray transitions to fit:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "Comma-delimeted list of <element><space><K or L or M> that will be fit in each xrf spectrum. This will be filled in with the above button but can be edited before exiting this window.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Xray transitions to quantify:", None, QtGui.QApplication.UnicodeUTF8))
        self.quantLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "Comma-delimeted list of <element><space><K or L or M> that will not only be fit but whose intesity will be used in the thin film calcualtions. This will be filled in with the above button but can be edited before exiting this window.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Background counts for quant transitions:", None, QtGui.QApplication.UnicodeUTF8))
        self.bckndLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "Comma-delimeted number for each quant transition - we default to 0. After the fitted instensity of a transition is obtained, it will be decreased by this amount before calculation of the thin film model. This is how elements that appear in the \"background\" are treated.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "Energy (keV) range for transitions:\n"
"             min    |    max", None, QtGui.QApplication.UnicodeUTF8))
        self.transitionsPushButton.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "This will use the above info to assemble a list of xray transitions to fit and use in quantification of the composition spread thin film.", None, QtGui.QApplication.UnicodeUTF8))
        self.transitionsPushButton.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "assemble lists of xray transitions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "density for quant elements:", None, QtGui.QApplication.UnicodeUTF8))
        self.densityLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Must be one for every quant element. The elemental densities will appear automatically but can be changed to known values for the particular chemistry. These values effect the mass attenuation calculation and are important in the determination of film thickness from the calculated mass thickness.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "mass for quant elements:", None, QtGui.QApplication.UnicodeUTF8))
        self.massLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Must be one for every quant element. The elemental masses will appear automatically but can be changed to known values for the particular chemistry. These values are important in the determination of film composition from the calculated mass fractions.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "nominal composition of quant elements:", None, QtGui.QApplication.UnicodeUTF8))
        self.compLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "This will be the starting estimate for each point, unless \"Use Dep. Profile Estimates\" is selected.", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "The \"flux\" value used in calculations will by default be taken from the .cfg file selected below (or can be entered or calculated, as indicated above) - this field should contain a dataset from the .h5 measurement/scalar_data group that will be multiplied by the flux to attain the xray dose.", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLineEdit.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "IC3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "scalar_data field to use as \"time\":", None, QtGui.QApplication.UnicodeUTF8))
        self.repenLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "To check if secondary excitation is contributing to quant transition, a model will be created where the incident beam will be modeled as a multi-energy beam with contribution from each quant element with intensity proportional to the measured concentration and energy indicated in this list.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "repr. energy (keV) of quant elements:", None, QtGui.QApplication.UnicodeUTF8))
        self.dlambdaLineEdit.setToolTip(QtGui.QApplication.translate("XRFAnalysisDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Functions for the film density and \"accounted for\" film mass fraction can be provided as \"lambda\" functions for the array of compositions c. The only objects that can be used in the lambda are the arrays of densities \"d\" and masses \"M\". If a \"lambda i\" is also provided, i is assumed to be the spec index (this must be the outer fcn, i.e. \"lambda i: lambda c: &lt;logic&gt;\").</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">For example, if left blank, the density default is \"lambda c: (d*c).sum()\" and mass fraction default is \"lambda c: 1.\"</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">EXAMPLE FOR SpecIndex-DEPENDENT DENSITY: weighted density is enhanced by 1.1 for SpecInd&lt;10:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">lambda i: (i&lt;10 and (lambda c: (1.1*d*c).sum())) or (lambda c: (d*c).sum())</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">EXAMPLE FOR COMPOSITON-DEPENDENT DENSITY: element 0 has density enhancement of 1.2 at low conc and 1.1 at mid:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">lambda c: (c[0]&gt;0.7 and (d*c).sum()) or (c[0]&gt;0.5 and (d*c)[0]*1.1+(d*c)[1:].sum()) or (d*c)[0]*1.2+(d*c)[1:].sum()</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">EXAMPLE FOR COMPOSITON-DEPENDENT MASS FRACTION: For Y2O3-ZrO2 composit with Y as element 0 and Zr as element 1, the \"quant elements\" does not include the mass of oxygen. The oxygen stoichiometry is 2 - half the Y:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">lambda c: (c*M).sum()/((c*M).sum()+16.*(2.-c[0]/2.))</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "lambda function for fraction of film mass accounted for in \"quant elements\" (or blank):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("XRFAnalysisDialog", "density lambda function (or blank):", None, QtGui.QApplication.UnicodeUTF8))

