#!/usr/bin/env python

import sys

from PyQt4 import QtGui

from spectromicroscopy.smpgui.smpmainwindow import SmpMainWindow

app = QtGui.QApplication(sys.argv)
app.setOrganizationName('CHESS')
app.setOrganizationDomain('cornell.edu')
app.setApplicationName('smp')
myapp = SmpMainWindow()
myapp.show()
sys.exit(app.exec_())
