#!/usr/bin/env python

import sys

from PyQt4 import QtGui

from spectromicroscopy.smpgui import SmpMainWindow

app = QtGui.QApplication(sys.argv)
myapp = SmpMainWindow()
myapp.show()
sys.exit(app.exec_())
