#!/usr/bin/env python

import sys

from PyQt4 import QtGui

from xpaxs.spectromicroscopy.ui import mainwindow

app = QtGui.QApplication(sys.argv)
app.setOrganizationName('CHESS')
app.setOrganizationDomain('cornell.edu')
app.setApplicationName('SMP')
myapp = mainwindow.MainWindow()
myapp.show()
sys.exit(app.exec_())
