#!/usr/bin/env python

from __future__ import absolute_import

#import signal
#signal.signal(signal.SIGINT, signal.SIG_DFL)

import logging
import sys

from PyQt4 import QtGui

from praxes.frontend import mainwindow

# TODO: this would be handled differently through the envisage framework:
from praxes.frontend.application import PraxesApplication

app = PraxesApplication(sys.argv)
app.setOrganizationName('Praxes')
app.setApplicationName('sxfm')
myapp = mainwindow.MainWindow()
myapp.show()

logger = logging.getLogger('praxes')
logger.debug('sxfm started')

sys.exit(app.exec_())
