#!/usr/bin/env python

#import signal
#signal.signal(signal.SIGINT, signal.SIG_DFL)

import logging
import sys

from PyQt4 import QtGui

from xpaxs.spectromicroscopy.ui import mainwindow

app = QtGui.QApplication(sys.argv)
app.setOrganizationName('XPaXS')
app.setApplicationName('SFXM')
myapp = mainwindow.MainWindow()
myapp.show()

logger = logging.getLogger('XPaXS.sxfm')
logger.debug('sxfm started')

sys.exit(app.exec_())
