#!/usr/bin/env python

#import signal
#signal.signal(signal.SIGINT, signal.SIG_DFL)

import logging
import sys

from PyQt4 import QtGui

from xpaxs.frontend import mainwindow

# TODO: this would be handled differently through the envisage framework:
from xpaxs.frontend.application import XpaxsApplication

app = XpaxsApplication(sys.argv)
app.setOrganizationName('XPaXS')
app.setApplicationName('xpaxs')
myapp = mainwindow.MainWindow()
myapp.show()

logger = logging.getLogger('xpaxs')
logger.debug('xpaxs started')

sys.exit(app.exec_())
