package:
  name: praxes
  version: master

source:
  git_url: https://github.com/praxes/praxes.git
  git_tag: master

build:
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - pyqt
  run:
    - python
    - numpy
    - pyqt
    - pymca
    - matplotlib
    - h5py
    - quantities

test:
  imports:
    - praxes

about:
  license: BSD
  home: http://pythonhosted.org/praxes/
  summary: Resources for synchrotron data analysis

