package:
  name: praxes
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  detect_binary_files_with_prefix: true
  osx_is_app: yes
#  entry_points:
#    - sxfm = praxes.cli.sxfm:main
#
#app:
#  entry: sxfm
#  summary: Scanning x-ray fluorescence microscopy analysis

requirements:
  build:
    - python
    - cython
    - numpy
    - pyqt
  run:
    - python
    - numpy
    - pyqt
    - pymca
    - matplotlib
    - h5py
    - quantities

test:
  imports:
    - praxes

about:
  license: BSD
  home: http://pythonhosted.org/praxes/
  summary: Resources for synchrotron data analysis
